server:
  port: 9090

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

turbine:
  appConfig: ribbon-consumer,ribbon-consumer,compute-service
  clusterNameExpression: "'default'"
spring:
  application:
    name: turbine